import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
 
// Font files can be colocated inside of `pages`
// Font files can be colocated inside of `pages`
const myFont = localFont({ src: './fonts/Aeonik-Regular.ttf' })

// const myFont = localFont({
//    src: [
//     {
//       path:'./fonts/Aeonik-Regular.ttf',
//       weight: '400',
//       style: 'normal',
//     },
//     {
//       path:'./fonts/Aeonik-Light.ttf',
//       weight: '300',
//       style: 'normal',
//     }
//   ]
// })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={myFont.className}
      >
        {children}
      </body>
    </html>
  );
}
